<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My Webpage</title>
    </head>
    <style>
        body {
           background-color:rgb(10, 255, 255);
           font-family:fantasy;
           font-size:30px;
           color: rgb(13, 109, 122);
          }
        #style {
          background-color: rgb(240, 144, 218);
          width:50%;
          padding: 15px;
          margin: auto;
          border:6px dashed rgb(13, 109, 122)
          }
          #cool {
            width:100;
            height:100;
          }
    </style>
    <body><div id="style">
        <h1>THE CODE ARTIST</h1>
        <p> Do you want a Webpage for your small business but don't want to do all the work? Let me do it for you! All you have to do is follow the instructions below!</p>
        
        <ol  align="center">
            <li><img id="cool" src="https://www.carolecgood.com/think-elec.jpg" >Think of what you want on your webpage.</li>
            <li><img id="cool" src="https://logos.flamingtext.com/Word-Logos/choose-design-sketch-name.png"> Choose some image's you want on you webpage</li>
            <li><img id="cool" src="https://cdn.instructables.com/FL2/5KAS/I7MXEMQ0/FL25KASI7MXEMQ0.LARGE.jpg" >Email it to me at Nacesha2004@gmail.com, such as... </li>
        </ol>
        <ul>
            <li> what your business is...</li>
            <li> your business name...</li>
            <li> your idea's for your webpage...</li>
            <li> your contact information!</li>
        
        </ul>
        </div>
    </body>
</html>
